### ISSUE TITLE
Feedback for OpenFGA team

### ISSUE THREAD

**Issue by aaguiarz** [bytefish/OpenFgaExperiments#1]
Hi @bytefish 

We'd love to learn about the outcome of your research for integrating OpenFGA with OData :) 

Thanks in advance!

**Comment by bytefish** [comment]
Thanks for the offer!

First of all it’s really super, super easy with Docker to start an OpenFGA instance and start experimenting with it right away. You did a great job. I also like the sample-stores repository, because I can see how more knowledgeable people build the Authorization models.

The OpenFGA documentation explains the various Google Zanzibar operations very well. The section on the ListObjects API for example is very interesting and shows when it’s better to filter on application-side and call the Check API on each item.

I didn’t experiment with the Playground yet, but I think it looks like a good “REPL” to try statements on your Authorization Models… without having to implement anything in your applications. I think it’s like playing around with SQL Statements, before actually integrating them into my application.

What’s currently lacking, and I totally get OpenFGA is just getting off the ground, is end-to-end examples in various languages. It’s hard to find out about best practices in various ecosystems. What works? What doesn’t work? How would I use it with an ORM? Where would I put my authorization checks?

So while researching Relationship-based Authorization, I have looked at SpiceDB, OSO, OpenFGA repositories… and I saw the OSO team has a set of Python end-to-end examples, with Angular Frontends. 

That makes it easy to understand, how they think their API SDK and Cloud Service is best used with the most important Python ORM (SQL Alchemy) and how you could combine it with an Angular Front end. 

That’s what a lot of “Enterprise Development” shops want to do, and I totally get why they have chosen the stack:

- https://github.com/osohq/gitcloud/tree/main

As a food for thought here. 

It would be interesting to see, how the “gitcloud” example would be modeled in OpenFGA and what abstractions would have to be built when using OpenFGA. 

I think the sample-stores repository already comes with a GitHub permission model? You could adapt it and a direct comparison would help tremendously… and wouldn’t be a huge invest. 

Before finding “gitcloud”, I came up with quite similar .NET abstractions for OpenFGA, to make it easier in .NET. Like I want to work with strongly typed objects and use them together with EntityFramework Core, which is what most people want to do in .NET: 

- https://github.com/bytefish/OpenFgaExperiments/blob/main/src/Server/RebacExperiments.Server.Api/Services/AclService.cs

Don’t get me wrong. I don’t expect any of these abstractions in the OpenFGA SDK. This is very specific to every application and it will differ from application to application, like a lot of people would really, really hate how I am throwing Exceptions. 🤷‍♂️ 

So as someone wanting to integrate OpenFGA I would like to know about some “proven” ideas, where to put my authorization checks for example. I have to give estimations to my Scrum overlords. 🫣

That said, a lot of what’s in this repository right now is still doing ground work, also with Blazor and ASP.NET Core OData, so I have a blueprint to steal from.

**Comment by aaguiarz** [comment]
Hi Philipp!

I apologize for the delay answering, we had a team offsite and later I had a week of PTO :).

Thanks for the feedback about having a good sample application. It's something we had in our list for a while, we actually were 90% done but never wrapped it up.

I've checked the AclService class and it has some pretty good ideas, like mapping the .NET class name to the OpenFGA object type automatically, which simplifies things. 

An idea we've been thinking about is to generate a strong-typed SDK that's coupled with the model, e.g.

```
class AclService 
{
       public static Task<bool> CanViewDocument(string subjectId, string documentId)
       {
             return await _openFgaClient.check( user: "user:{id}", relation : "can_view", object: "document:{documentId}")
       }
}
```

But that will probably make it more difficult to use for an OData integration point of view.

Regarding using the Playground as a "REPL" tool, you can also do that with out [VS Code integration](https://github.com/openfga/vscode-ext) and our [CLI](https://github.com/openfga/cli), in case you missed it.

Let us know if you end up moving forward with using OpenFGA in production!

Cheers
